import re
import hashlib
from typing import Optional, Set, Tuple, List
from urllib.parse import urljoin, urlparse


def calculate_sha256(text: str) -> Optional[str]:
    """Compute SHA-256 hash of cleaned text for change detection."""
    if not text:
        return None
    h = hashlib.sha256()
    h.update(text.encode("utf-8"))
    return h.hexdigest()


def format_to_clean_markdown(title: str, url: str, raw_markdown: str) -> str:
    """Standardizes markdown headers and strips extraneous whitespace and navigation artifacts."""
    if not raw_markdown:
        return ""

    cleaned = raw_markdown.strip()

    # Remove UI artifacts such as skip links and standalone material icon labels
    cleaned = re.sub(r"\[\s*Skip To Main Content\s*\]\([^)]+\)", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"(?m)^\s*(chevron_right|info|search|menu|expand_more)\s*$", "", cleaned)
    cleaned = re.sub(r"(?m)^\s*Courier New\s*\(Serif\)\s*$", "", cleaned, flags=re.IGNORECASE)

    # Remove codeblock fences generated by Crawl4AI for HTML <pre> containers in legal texts
    cleaned = re.sub(r"(?m)^```[a-zA-Z0-9_-]*\s*$", "", cleaned)

    # Clean whitespace-only lines
    cleaned = re.sub(r"(?m)^[ \t]+$", "", cleaned)

    # Normalize excessive newlines
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned.strip())

    # Build standardized document header
    header = f"# {title}\n\n"
    header += f"- **Official Source URL**: {url}\n"
    header += "---\n\n"

    return header + cleaned


def is_allowed_domain(url: str, allowed_domains: List[str]) -> bool:
    """Verifies if the URL matches configured allowed domains."""
    try:
        parsed = urlparse(url)
        netloc = parsed.netloc.lower().split(":")[0]
        if not netloc:
            return False
        return any(netloc == d.lower() or netloc.endswith("." + d.lower()) for d in allowed_domains)
    except Exception:
        return False


def is_binary_download(url: str) -> bool:
    """Prevents crawler crashes from non-HTML/PDF binary file downloads."""
    try:
        parsed = urlparse(url)
        path_lower = parsed.path.lower()
        binary_extensions = (".doc", ".docx", ".zip", ".tar", ".gz", ".exe", ".xlsx", ".xls", ".csv", ".mp3", ".mp4")
        if path_lower.endswith(binary_extensions):
            return True
        query_lower = parsed.query.lower()
        return any(f".{ext}" in query_lower for ext in ["doc", "docx", "zip", "xlsx", "csv", "exe"])
    except Exception:
        return False


def is_pdf_url(url: str) -> bool:
    """Detects whether a URL represents a PDF document via file extension or query parameter."""
    try:
        parsed = urlparse(url)
        path_lower = parsed.path.lower()
        if path_lower.endswith(".pdf"):
            return True
        query_lower = parsed.query.lower()
        pdf_indicators = ["pdf=true", "pdf=1", "format=pdf", "type=pdf", "export=pdf", "output=pdf", "download=pdf", ".pdf"]
        return any(indicator in query_lower for indicator in pdf_indicators)
    except Exception:
        return False


def classify_links(
    links: List[str], 
    base_url: str, 
    allowed_domains: List[str]
) -> Tuple[Set[str], Set[str]]:
    """
    Categorizes raw Crawl4AI extracted links into HTML sub-pages and PDF downloads.
    """
    discovered_html: Set[str] = set()
    discovered_pdf: Set[str] = set()

    for link in links:
        if not link:
            continue
            
        abs_url = urljoin(base_url, link.strip()).split("#")[0]

        if not abs_url.startswith(("http://", "https://")):
            continue
        if allowed_domains and not is_allowed_domain(abs_url, allowed_domains):
            continue
        if is_binary_download(abs_url):
            continue

        if is_pdf_url(abs_url):
            discovered_pdf.add(abs_url)
        elif abs_url != base_url:
            discovered_html.add(abs_url)

    return discovered_html, discovered_pdf